version: "3"
services:
  app:
      image: node:alpine
      volumes:
        - ./:/app
      working_dir: /app
      environment:
        NODE_ENV: production
        VIRTUAL_HOST: editor.wedev.org
        VIRTUAL_PORT: 3000
      ports:
        - 3000:3000
      expose:
        - 3000
      command: npm run start
networks:
  default:
    external:
      name: webproxy