version: "3"
services:
  app:
      container_name: editor-wedev-org
      image: node:alpine
      volumes:
        - ./:/app
      working_dir: /app
      environment:
        NODE_ENV: production
        VIRTUAL_HOST: editor.wedev.org
        VIRTUAL_PORT: 3000
        LETSENCRYPT_HOST: editor.wedev.org
        LETSENCRYPT_EMAIL: arancibiajav@gmail.com
      ports:
        - 3000:3000
      command: npm run start
networks:
  default:
    external:
      name: webproxy
